/** ACTIONS */
const ADMIN 			= { '*': {} }
const READ 				= { 'read': {} }
const ROLE 				= { 'role': ['Invoice Payers'] }

/** FEATURES */
const HOME				= 'home'
const MESSAGES 			= 'messages'
const REPORTS 			= 'reports'
const SCRIPTS			= 'scripts'
const STRIPE 			= 'stripe'
const SUPER 			= '*'
const WORKFLOW			= 'workflow'

/** INSTANCES */
const INSTANCE_DEV		= 'dev'
const INSTANCE_ROXANE 	= 'Roxane'
const INSTANCE_SUPER 	= '*'

const PERMISSIONS_SET1 = {
	[HOME]: ADMIN,
	[WORKFLOW]: ROLE
}
const PERMISSIONS_SET2 = {
	[HOME]: ADMIN,
	[REPORTS]: READ,
	[WORKFLOW]: ROLE
}
const PERMISSIONS_SET3 = {
	[REPORTS]: READ,
	[SCRIPTS]: ADMIN,
	[SUPER]: ADMIN
}
const PERMISSIONS_SET4 = {
	[REPORTS]: READ,
	[SCRIPTS]: ADMIN,
	[SUPER]: READ
}
const PERMISSIONS_SET5 = {
	[MESSAGES]: ADMIN,
	[STRIPE]: READ
}
const PERMISSIONS_SET6 = {
	[HOME]: ADMIN,
	[STRIPE]: READ
}
const PERMISSIONS_SET7 = {
	[SUPER]: ADMIN
}
const PERMISSIONS_SET8 = {
	[HOME]: READ,
	[MESSAGES]: READ
}
const PERMISSIONS_SET9 = {
	[HOME]: ADMIN,
	[MESSAGES]: READ,
	[STRIPE]: READ
}
const PERMISSIONS_SET10 = {
	[HOME]: ADMIN,
	[STRIPE]: ADMIN
}

const INSTANCE_SET1 = {
	[INSTANCE_ROXANE]: PERMISSIONS_SET2
}
const INSTANCE_SET2 = {
	[INSTANCE_ROXANE]: PERMISSIONS_SET2,
	[INSTANCE_DEV]: PERMISSIONS_SET6
}
const INSTANCE_SET3 = {
	[INSTANCE_ROXANE]: PERMISSIONS_SET2,
	[INSTANCE_SUPER]: PERMISSIONS_SET6
}
const INSTANCE_SET4 = {
	[INSTANCE_ROXANE]: PERMISSIONS_SET10
}
const INSTANCE_SET5 = {
	[INSTANCE_ROXANE]: PERMISSIONS_SET7
}
const INSTANCE_SET6 = {
	[INSTANCE_ROXANE]: PERMISSIONS_SET2,
	[INSTANCE_SUPER]: PERMISSIONS_SET7
}

module.exports = {
	ADMIN,
	READ,
	ROLE,
	HOME,
	MESSAGES,
	REPORTS,
	SCRIPTS,
	STRIPE,
	SUPER,
	WORKFLOW,
	INSTANCE_DEV,
	INSTANCE_ROXANE,
	INSTANCE_SUPER,
	PERMISSIONS_SET1,
	PERMISSIONS_SET2,
	PERMISSIONS_SET3,
	PERMISSIONS_SET4,
	PERMISSIONS_SET5,
	PERMISSIONS_SET6,
	PERMISSIONS_SET7,
	PERMISSIONS_SET8,
	PERMISSIONS_SET9,
	PERMISSIONS_SET10,
	INSTANCE_SET1,
	INSTANCE_SET2,
	INSTANCE_SET3,
	INSTANCE_SET4,
	INSTANCE_SET5,
	INSTANCE_SET6
}
