const ID_SEPARATOR = '.'
const HEADER_KEY_PREFIX = `b2${ID_SEPARATOR}`
const PLATFORM6 = 'platform6'
const PLATFORM6_APP_KEY = PLATFORM6 + ID_SEPARATOR
const RECEIVER_ID_PREFIX = `cmb${ID_SEPARATOR}`
const SENDER_ID_PREFIX = `tmp${ID_SEPARATOR}`

export const Constants = {
	HEADER_KEY_PREFIX,
	PLATFORM6,
	PLATFORM6_APP_KEY,
	RECEIVER_ID_PREFIX,
	SENDER_ID_PREFIX,
	ID_SEPARATOR,
	ACTION_DEPLOY: 'deploy',
	SERVICE_MANAGER_ID: `${PLATFORM6_APP_KEY}manager`,
	SERVICE_SCRIPTS_ID: `${PLATFORM6_APP_KEY}scripts`,
	USER_KEY: `${HEADER_KEY_PREFIX}user`,
}
