const SEPARATOR = '.'
const HEADER_KEY_PREFIX = `b2${SEPARATOR}`
const PLATFORM6_APP_KEY = `platform6${SEPARATOR}`
const RECEIVER_ID_PREFIX = `cmb${SEPARATOR}`
const SENDER_ID_PREFIX = `tmb${SEPARATOR}`

export const Constants = {
	HEADER_KEY_PREFIX,
	PLATFORM6_APP_KEY,
	RECEIVER_ID_PREFIX,
	SENDER_ID_PREFIX,
	SEPARATOR,
	ACTION_DEPLOY: 'deploy',
	SERVICE_MANAGER_ID: `${PLATFORM6_APP_KEY}manager`,
	SERVICE_SCRIPTS_ID: `${PLATFORM6_APP_KEY}scripts`,
	USER_KEY: `${HEADER_KEY_PREFIX}user`,
}
